import type { Metadata } from "next";
import '../globals.css'
import Header from "@/components/main/Header";
import Footer from "@/components/main/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='w-[100vw] px-[10%] relative overflow-x-hidden bg-white chillax-font cursor-default'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
